### ISSUE TITLE
大佬是否会出现疑似作弊

### ISSUE THREAD

**Issue by qud123** [zycn0910/Sign-ZXJY#1]
大佬测试过了吗
是否会出现疑似作弊

**Comment by zycn0910** [comment]
我这边测试14个账号，暂未出现异常

**Comment by qud123** [comment]
好的好的
| |
小梁长不胖
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月16日 18:17 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [zycn0910/Sign-ZXJY] 大佬是否会出现疑似作弊 (Issue #1) |

我这边测试14个账号，暂未出现异常

**Comment by qud123** [comment]
大佬如果设置成每天任何时间运行都推送怎么设置时间我改成00-24不太行

**Comment by zycn0910** [comment]
重新拉取一下代码，留空即为全时段推送

**Comment by qud123** [comment]
OK 👌

**Comment by qud123** [comment]
> 重新拉取一下代码，留空即为全时段推送

大佬咋不整个那个日报周报月报 嘿嘿是不是有点得寸进尺了哈哈哈哈

**Comment by zycn0910** [comment]
暂不考虑

**Comment by qud123** [comment]
挂服务器3个账号出现两个系统繁忙

**Comment by zycn0910** [comment]
main.py第205行，waittime设置成5以上即可

**Comment by qud123** [comment]
我设置成了30，他两个出了一个繁忙，昨天在本地没事，今天一放服务器就这样，可能是ip的问题

**Comment by zycn0910** [comment]
云函数大概率会繁忙，我的使用环境是青龙面板，只有waittime小于2才会出现繁忙

**Comment by qud123** [comment]
我放在了宝塔python项目然后计划任务执行的😂

**Comment by zycn0910** [comment]
任务日志可以适当打码发一下看看

**Comment by qud123** [comment]
明天繁忙了我再发出来，今天的我删了😂

**Comment by zycn0910** [comment]
应该是你的ip问题，我在宝塔环境下运行，waittime为3时一切正常

**Comment by qud123** [comment]
阿里云白嫖的服务器，等会我换腾讯的试试😂

**Comment by qud123** [comment]
阿里云白嫖的服务器，等会我换腾讯的试试😂

**Comment by qud123** [comment]
确实是服务器问题，我今天本地运行的没一点问题

**Comment by qud123** [comment]
按理说阿里云的服务器没理由系统繁忙吧😅

**Comment by qud123** [comment]
腾讯云也繁忙昨天试了大佬有没有什么好的解决方案

**Comment by zycn0910** [comment]
代理池，爱加速，应该都可以，但是不建议，打卡ip不建议常换

**Comment by qud123** [comment]
今天设置打卡时间11.不会繁忙了。谢谢大佬，可能太早人多

**Comment by qud123** [comment]
今天我这有个傻缺朋友疑似作弊说连续5天都疑似作弊，他给我的地址是省市县加了个国道，距离他实习地方几十公里，我给他说他给我的地址有问题他还给我抬杠

**Comment by zycn0910** [comment]
建议用营业执照上的地址
