### ISSUE TITLE
青龙怎么使用

### ISSUE THREAD

**Issue by good8ai** [zycn0910/Sign-ZXJY#11]
您好老哥 青龙怎么使用 有没有拉库链接 我自己弄半天弄不好

**Comment by zycn0910** [comment]
青龙面板
定时任务早7点和10点运行一次：
![image](https://github.com/zycn0910/Sign-ZXJY/assets/46790182/b73cffb2-1789-45ba-b736-e23c903abfd3)
依赖安装：
![image](https://github.com/zycn0910/Sign-ZXJY/assets/46790182/f5fdacb9-5740-4810-8870-01ead98bb69d)
脚本目录，注意定时任务的命令：
![image](https://github.com/zycn0910/Sign-ZXJY/assets/46790182/4e261fec-9d6b-4adf-a448-fb488e82405c)

**Comment by good8ai** [comment]
![Snipaste_2023-11-04_23-21-12](https://github.com/zycn0910/Sign-ZXJY/assets/127216467/bae18700-6748-412a-8d60-85aeb23c30cd)
您好 我按照您的1流程安装完了所以依赖 也导入了所有文件 咋还是报错

**Comment by zycn0910** [comment]
用python3运行

**Comment by good8ai** [comment]
![image](https://github.com/zycn0910/Sign-ZXJY/assets/127216467/89afea04-df1c-472c-9da8-b75c1ffe4e5c)
nin您好我跟着您最新的青龙教程走运行还是这样报错 呜呜呜

**Comment by zycn0910** [comment]
你青龙面板版本是多少

**Comment by good8ai** [comment]
2.16.4

**Comment by zycn0910** [comment]
你看redme里面的青龙教程
