### ISSUE TITLE
我自行加入了动态ip池进行打卡，这样有没有用？有没有起到防作弊等等问题之类的？

### ISSUE THREAD

**Issue by MGinger520** [zycn0910/Sign-ZXJY#13]
我自己进行加入了动态ip池进行打卡，这样有没有用？有没有起到防作弊等等问题之类的？

**Comment by zycn0910** [comment]
一个账号最好固定一个ip，最好是挂名公司身份市区的，否则意义不大

**Comment by MGinger520** [comment]
如果这样的话，我取消动态，跟着服务器的ip走（广州的）这样一直打卡，问题不大吧？
