### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by good8ai** [zycn0910/Sign-ZXJY#21]
![image](https://github.com/zycn0910/Sign-ZXJY/assets/127216467/18c23353-c896-425e-9f18-8ab8fe5cd43a)
da大佬 昨天运行还正常 今天 运行一直卡在这里 拉库最新版也是这样 这个是什么导致哒

**Comment by zycn0910** [comment]
青龙面板的实时日志显示有延迟，我建议你开始运行后等（用户数量*30s）的时间后再去任务日志栏内查看青龙的日志

**Comment by good8ai** [comment]
您好 还是这样 好像就卡在这里 了 然后也没有签到

**Comment by good8ai** [comment]
![image](https://github.com/zycn0910/Sign-ZXJY/assets/127216467/8141accd-764c-4729-b409-60f01f7b5504)
![image](https://github.com/zycn0910/Sign-ZXJY/assets/127216467/48062a42-6540-4d53-928f-9da643b967f0)
da大佬这是报错日志 能看出来哪里的问题嘛

**Comment by zycn0910** [comment]
你这不纯纯网络问题吗…

**Comment by good8ai** [comment]
啊 对不起 打开成功了。。。好奇怪。。
