### ISSUE TITLE
12.30 失效

### ISSUE THREAD

**Issue by iuuuuuuuu** [zycn0910/Sign-ZXJY#33]
系统平台（Windows、Linux、云函数）：

config.py内开启了什么功能：

问题详细描述（怎么发现的问题）：获取Token失败无法打卡

终端报错输出（最后几行即可）：

日志（config.py内log改为Tru后，在log文件夹下查看）：

**Comment by zycn0910** [comment]
你的日志呢，我这的账号全没报错

**Comment by iuuuuuuuu** [comment]
我刚又试了一下成功了 原来是 clash 代理寄了 然后导致不能请求

**Comment by iuuuuuuuu** [comment]
> 你的日志呢，我这的账号全没报错
我刚又试了一下成功了 原来是 clash 代理寄了 然后导致不能请求
